### ISSUE TITLE
Remove the docker push from the travis commands

### ISSUE THREAD

**Issue by NathanSkene** [NathanSkene/EWCE#25]
Shouldn't be necessary as docker hub should build it automatically

**Comment by NathanSkene** [comment]
Hey Alan, just as a bit of clarification on this. I setup travis over summer, and added code so that after a successful build it pushes to dockerhub. I then realised, that this is not actually necessary, from what I understand Dockerhub should see that there has been a commit to github and it should build within my dockerhub profile.

I think this needs to be removed:

```
# This is intended to run Docker only when the build on linux/release is completed succesfully on the master branch
deploy:
  provider: script
  script: bash docker_push
  skip_cleanup: true
  on:
    branch: master
    condition: "$TRAVIS_OS_NAME = linux && $TRAVIS_R_VERSION_STRING = 'release'"
```

This is the current page on dockerhub:

https://hub.docker.com/repository/docker/nathanskene/ewce

Would be good if you could check that I'm right that dockerhub should build it itself, and then remove the travis code. Probably best to wait until we've got changes ready to push to master though, to ensure it notices there are changes to update.
